name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.1.0
  google_sign_in: 5.4.2
  firebase_auth: 4.0.2
  lottie: 1.4.3
  social_login_buttons: 1.0.6+2
  avatar_glow: 2.0.2
  cloud_firestore: 4.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/icon/
  uses-material-design: true

